name: Deploy frontend SSR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: actions-deploy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 20 with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'                          # pnpm вместо npm!
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile     # pnpm ci аналог

      - name: Build
        run: pnpm run build                     # без working-directory!

      - name: Upload app via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: ".output/* package.json pnpm-lock.yaml"  # только нужное
          target: "/var/www/electronics-store-front"
          rm: true

      - name: Restart frontend service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/electronics-store-front
            sudo systemctl daemon-reload
            sudo systemctl restart ${{ secrets.FRONT_SERVICE_NAME }}
